import random
import time
import subprocess
import os
import sys

def chooseDir():
    print ("Current Directory: " + os.getcwd())
    answer = input("Would you like to change it? (y/n): ").lower().strip()
    while not (answer == "y" or answer == "yes" or answer == "n" or answer == "no"):
        print("Please give a valid input")
        answer = input("Would you like to change it? (y/n): ").lower().strip()
    if answer[0] == "y":
        newDir = input("New Directory (Copy and Paste): ")
        while os.path.isdir(newDir) == False:
            print ("Not a valid directory!")
            newDir = input("New Directory (Copy and Paste): ")
        newDir = os.path.normcase(newDir)
        os.chdir(newDir)
    print ("Current Directory: " + os.getcwd())
    print ('Files in Directory:')
    file_list = '\n'.join(os.listdir('.'))
    print(file_list)
    answerFile = input("Name of answer file (include the file extension): ")
    while os.path.isfile(answerFile) == False:
        print ('Error! File does not exist!\nPlease try again')
        answerFile = input("Name of answer file (include the file extension): ")
    questionFile = input("Name of question file (include the file extension): ")
    while os.path.isfile(questionFile) == False:
        print ('Error! File does not exist!\nPlease try again')
        questionFile = input("Name of question file (include the file extension): ")
    ### because return answerFile,questionFile doesnt work
    global questionFile
    global answerFile
###
def lq(number):
    if number <= QuestionCount:
        f = open(questionFile, "r")
        question = ''
        for i, line in enumerate(f):
            if i == number:
                question = line.strip()
                break
        f.close()
        return question
    else:
        return "Error: Number too high"

def la(number):
    if number <= AnswerCount:
        f = open(answerFile, "r")
        answer = ''
        for i, line in enumerate(f):
            if i == number:
                answer = line.strip()
                break
        f.close()
        return answer
    else:
        return "Error: Number too high"

def init(Questionfile, Answerfile):
    count = 0
    for line in open(Questionfile, "r"):
        count += 1
    global QuestionCount
    QuestionCount = count
    ###
    count = 0
    for line in open(Answerfile, "r"):
        count += 1
    global AnswerCount
    AnswerCount = count

def EndOfQuiz(filename):
    print("These were your results: ")
    alist = [line.strip().split(',') for line in open(filename+'.tmp')]
    del alist[0]
    print (alist)
    questions = []
    answers = []
    for thing in alist:
        #questions.append(thing[:1])
        print("Question: " + str(thing[:1]))
        print(thing[1::2].strip())
        #answers.append(thing[3])
    print (questions)
    print (answers)
    correctA = 0
    wrongA = 0
    print (len(questions))
    for i in range(len(questions)):
        if answers[i] == 'Y':
            print("Answer correct :" +answers[i])
            correctA += 1
        elif answers[i] == 'N':
            print("Answer wrong :" +answers[i])
            wrongA += 1
    print ('Right: ' + str(correctA))
    print ('Wrong: ' + str(wrongA))
    allA = correctA + wrongA
    percentage = (correctA / allA) * 100
    print ('Percentage: ' + str(percentage) + '%')
    for i in range(0,QuestionCount):
        if answers[i] == 'N':
            print ('You got Question ' + questions[i] + ' wrong.')
            print (lq(i))
            print ('The correct answer was: ' + la(i))
    ###
    if os.path.exists(filename+'.tmp'):
        os.remove(filename+'.tmp')
    else:
        print("The file does not exist") 

def StartQuiz(Questionfile,Answerfile):
    init(Questionfile, Answerfile)
    if AnswerCount != QuestionCount:
        print ("Error, counts dont match")
    ###
    resultFile = "results"+str(random.randrange(0, 9999, 1))
    f = open(resultFile+".tmp", "w+")
    subprocess.check_call(["attrib","+H",resultFile])
    f.write("Autogenerated on " + time.asctime() + " by the quiz. The answers are stored here and at the end it is calculated how you have done. This decreases memory load." + "\n")
    ###
    q = ''
    for i in range(QuestionCount):
        q = lq(i).replace('? ', '?\n').replace('. B', '.\nB').replace('. C', '.\nC').replace('. D', '.\nD')
        print ("Question " + str(i+1) + ": " + q)
        if "TWO" in q:
            Answer1 = input("Answer (Choose first choice from A,B,C,D): " ).upper()
            if len(Answer1) > 1:
                print ("Only enter a single letter...")
                Answer1 = input("Answer (Choose first choice from A,B,C,D): " ).upper()
            Answer2 = input("Answer (Choose second choice from A,B,C,D): " ).upper()
            GivenAnswer = Answer1 + ', ' + Answer2
        elif "true" in q or "True" in q:
            GivenAnswer = input("Answer (Choose from TRUE or FALSE): " ).upper()
        elif "A" in q and "B" in q and "C" in q and "D" in q:
            GivenAnswer = input("Answer (Choose from A,B,C,D): " ).upper()
        elif "A" in q and "B" in q and "C" not in q and "D" not in q:
            GivenAnswer = input("Answer (Choose from A,B): " ).upper()
        CorrectA = la(i)
        if GivenAnswer == CorrectA:
            print("CORRECT")
            f.write(str(i + 1) + ", " + "Y"+"\n")
        else:
            print("WRONG, SORRY")
            f.write(str(i + 1) + ", " + "N"+"\n")
    f.close()
    print ("Finished test!")
    EndOfQuiz(resultFile)


###
chooseDir()
StartQuiz(questionFile, answerFile)















